spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db?currentSchema=account_service
    username: mend1001
    password: mend1001_2026

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: account_service
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html